# lib/env.sh — NaughtBot E2E environment state management.
#
# The harness writes a small env.sh file after setup completes so that
# run-test.sh / teardown.sh / status.sh pick up the same UDID, CLI path,
# URLs, and coordination directories without re-discovering them.
#
# Layout:
#   /tmp/nb-e2e/env.sh              (single-slot default)
#   /tmp/nb-e2e-slot-N/env.sh       (parallel slot N)
#   /tmp/nb-e2e-meta/parallel-count (written by setup.sh --parallel N)
#
# Selecting a slot is done purely through the NB_E2E_SLOT env var:
# setup.sh sets it per-slot while bootstrapping; run-test.sh sets it from
# `--slot N`; run-parallel.sh sets it per dispatched suite.
#
# This module defines pure shell functions; source it after common.sh.

if [[ -z "${_NB_ENV_SH_LOADED:-}" ]]; then
    _NB_ENV_SH_LOADED=1

    # -----------------------------------------------------------------------
    # Slot helpers
    # -----------------------------------------------------------------------
    # A slot is an integer >=1 for parallel runs, or empty/0 for the default
    # single-slot layout. Keeping this centralised lets phase 5 plug in
    # without changing any of the individual scripts.

    # nb_e2e_slot: echo the current slot number if set via
    # NB_E2E_SLOT (including "0"), else empty for single-slot mode.
    # Slots start from 0 in parallel mode; single-slot mode is indicated by
    # the variable being unset or empty.
    nb_e2e_slot() {
        local slot="${NB_E2E_SLOT:-}"
        echo "$slot"
    }

    nb_e2e_data_dir() {
        local slot
        slot="$(nb_e2e_slot)"
        if [[ -n "$slot" ]]; then
            echo "/tmp/nb-e2e-slot-$slot"
        else
            echo "/tmp/nb-e2e"
        fi
    }

    nb_e2e_config_dir() {
        local slot
        slot="$(nb_e2e_slot)"
        if [[ -n "$slot" ]]; then
            echo "/tmp/nb-e2e-config-slot-$slot"
        else
            # Timestamp + pid so each setup run gets a fresh CLI config root.
            local ts
            ts="$(date +%s)"
            echo "/tmp/nb-e2e-config-$ts-$$"
        fi
    }

    nb_e2e_env_file() {
        echo "$(nb_e2e_data_dir)/env.sh"
    }

    # -----------------------------------------------------------------------
    # Write / load env state.
    # -----------------------------------------------------------------------
    # write_env_file: takes a sequence of KEY=VALUE args, writes to env.sh
    # with quoted values so reloading via `source` is safe.

    write_env_file() {
        local env_path
        env_path="$(nb_e2e_env_file)"
        local dir
        dir="$(dirname "$env_path")"
        mkdir -p "$dir"
        {
            echo "# NaughtBot E2E environment snapshot — generated by setup.sh."
            echo "# Sourced by run-test.sh / teardown.sh / status.sh."
            echo "# Regenerate by re-running ./setup.sh."
            echo ""
            local pair key value
            for pair in "$@"; do
                key="${pair%%=*}"
                value="${pair#*=}"
                # Use printf %q to safely single-quote arbitrary values.
                printf 'export %s=%q\n' "$key" "$value"
            done
        } >"$env_path"
        log_info "wrote env snapshot: $env_path"
    }

    load_env_file() {
        local env_path
        env_path="$(nb_e2e_env_file)"
        if [[ ! -f "$env_path" ]]; then
            log_error "env.sh not found at $env_path — run ./setup.sh first"
            return 1
        fi
        # shellcheck disable=SC1090
        source "$env_path"
        log_info "loaded env snapshot: $env_path"
    }

    # -----------------------------------------------------------------------
    # Health checks.
    # -----------------------------------------------------------------------
    # is_stack_healthy: returns 0 when gateway responds and the backend
    # management endpoints answer on their localhost-only published ports.
    # --quick variant intended for status.sh.

    identity_management_url() {
        echo "${IDENTITY_MANAGEMENT_URL:-http://127.0.0.1:9091}"
    }

    blob_management_url() {
        echo "${BLOB_MANAGEMENT_URL:-http://127.0.0.1:9092}"
    }

    relay_management_url() {
        echo "${RELAY_MANAGEMENT_URL:-http://127.0.0.1:9093}"
    }

    is_stack_healthy() {
        curl -fsS "http://127.0.0.1:4455/.well-known/openid-configuration" >/dev/null 2>&1 || return 1
        curl -fsS "$(identity_management_url)/health" >/dev/null 2>&1 || return 1
        curl -fsS "$(blob_management_url)/health" >/dev/null 2>&1 || return 1
        curl -fsS "$(relay_management_url)/health" >/dev/null 2>&1 || return 1
        return 0
    }

    is_simulator_booted() {
        local udid="${1:-${SIMULATOR_ID:-}}"
        [[ -n "$udid" ]] || return 1
        xcrun simctl list devices | grep -E "^\s*.*\($udid\) \(Booted\)$" >/dev/null 2>&1
    }

    # -----------------------------------------------------------------------
    # Slot helpers (parallel execution).
    # -----------------------------------------------------------------------
    # A slot is an integer >=0. Each slot owns its own simulator, coordination
    # directory, and CLI config directory so multiple suites can run
    # concurrently against one shared backend docker stack.
    #
    # slot_state_dir  <N> → /tmp/nb-e2e-slot-<N>
    # slot_config_dir <N> → /tmp/nb-e2e-config-slot-<N>
    # slot_env_file   <N> → /tmp/nb-e2e-slot-<N>/env.sh

    NB_E2E_META_DIR="/tmp/nb-e2e-meta"

    slot_state_dir() {
        local slot="$1"
        echo "/tmp/nb-e2e-slot-$slot"
    }

    slot_config_dir() {
        local slot="$1"
        echo "/tmp/nb-e2e-config-slot-$slot"
    }

    slot_env_file() {
        local slot="$1"
        echo "$(slot_state_dir "$slot")/env.sh"
    }

    # write_slot_env_state <slot> <KEY=VALUE>...
    #
    # Writes the per-slot env.sh atomically. Every value is printf %q quoted
    # so reloading via `source` is safe regardless of whitespace or specials.
    write_slot_env_state() {
        local slot="$1"; shift
        local dir env_path
        dir="$(slot_state_dir "$slot")"
        env_path="$(slot_env_file "$slot")"
        mkdir -p "$dir"
        {
            echo "# NaughtBot E2E environment snapshot — slot $slot."
            echo "# Generated by setup.sh --parallel N."
            echo "# Sourced by run-test.sh --slot $slot / run-parallel.sh."
            echo ""
            local pair key value
            for pair in "$@"; do
                key="${pair%%=*}"
                value="${pair#*=}"
                printf 'export %s=%q\n' "$key" "$value"
            done
        } >"$env_path"
        log_info "wrote slot $slot env snapshot: $env_path"
    }

    # load_slot_env_state <slot>: source slot env.sh; returns 1 if missing.
    load_slot_env_state() {
        local slot="$1"
        local env_path
        env_path="$(slot_env_file "$slot")"
        if [[ ! -f "$env_path" ]]; then
            log_error "slot $slot env.sh not found at $env_path — run ./setup.sh --parallel N first"
            return 1
        fi
        # shellcheck disable=SC1090
        source "$env_path"
        log_info "loaded slot $slot env snapshot: $env_path"
    }

    # list_slots: emit one slot number per line, ascending.
    list_slots() {
        local f
        for f in /tmp/nb-e2e-slot-*/env.sh; do
            [[ -f "$f" ]] || continue
            local dir="${f%/env.sh}"
            echo "${dir##*-slot-}"
        done | sort -n
    }

    # write_parallel_count <N>: record the parallel slot count so later
    # invocations (run-parallel.sh, teardown.sh) can discover it.
    write_parallel_count() {
        local count="$1"
        mkdir -p "$NB_E2E_META_DIR"
        printf '%s\n' "$count" >"$NB_E2E_META_DIR/parallel-count"
    }

    # read_parallel_count: echo the recorded count, or empty if not present.
    read_parallel_count() {
        local f="$NB_E2E_META_DIR/parallel-count"
        if [[ -f "$f" ]]; then
            cat "$f"
        fi
    }

    # update_env_state_export <env-file> <key> <value>
    # Rewrite an existing `export KEY=...` line in-place, or append if missing.
    update_env_state_export() {
        local state_file="$1"
        local key="$2"
        local value="$3"
        [[ -f "$state_file" ]] || return 1
        local tmp
        tmp="$(mktemp)"
        if grep -q "^export ${key}=" "$state_file"; then
            awk -v key="$key" -v value="$value" '
                $0 ~ "^export " key "=" {
                    printf "export %s=%s\n", key, value
                    next
                }
                { print }
            ' "$state_file" >"$tmp"
        else
            cat "$state_file" >"$tmp"
            printf 'export %s=%s\n' "$key" "$value" >>"$tmp"
        fi
        mv "$tmp" "$state_file"
    }

    # mark_env_login_complete [<slot>]: set NB_E2E_LOGIN_DONE=1 in the
    # default or slot-specific env.sh. Uses printf %q quoting.
    mark_env_login_complete() {
        local slot="${1:-}"
        local state_file
        if [[ -n "$slot" ]]; then
            state_file="$(slot_env_file "$slot")"
        else
            state_file="$(nb_e2e_env_file)"
        fi
        update_env_state_export "$state_file" "NB_E2E_LOGIN_DONE" "$(printf '%q' 1)"
    }
fi
