// Package protocol provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package protocol

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AckAgentCommonApprovalAttestationV1Version.
const (
	ApprovalAttestationv1 AckAgentCommonApprovalAttestationV1Version = "approval-attestation/v1"
)

// Valid indicates whether the value is a known member of the AckAgentCommonApprovalAttestationV1Version enum.
func (e AckAgentCommonApprovalAttestationV1Version) Valid() bool {
	switch e {
	case ApprovalAttestationv1:
		return true
	default:
		return false
	}
}

// Defines values for AckAgentCommonApprovalAttestedKeyProofVersion.
const (
	ApprovalAttestedKeyProofv1 AckAgentCommonApprovalAttestedKeyProofVersion = "approval-attested-key-proof/v1"
)

// Valid indicates whether the value is a known member of the AckAgentCommonApprovalAttestedKeyProofVersion enum.
func (e AckAgentCommonApprovalAttestedKeyProofVersion) Valid() bool {
	switch e {
	case ApprovalAttestedKeyProofv1:
		return true
	default:
		return false
	}
}

// Defines values for AckAgentCommonApprovalChallengeVersion.
const (
	ApprovalChallengev1 AckAgentCommonApprovalChallengeVersion = "approval-challenge/v1"
)

// Valid indicates whether the value is a known member of the AckAgentCommonApprovalChallengeVersion enum.
func (e AckAgentCommonApprovalChallengeVersion) Valid() bool {
	switch e {
	case ApprovalChallengev1:
		return true
	default:
		return false
	}
}

// Defines values for AckAgentCommonApproverDeviceType.
const (
	Android AckAgentCommonApproverDeviceType = "android"
	Ios     AckAgentCommonApproverDeviceType = "ios"
)

// Valid indicates whether the value is a known member of the AckAgentCommonApproverDeviceType enum.
func (e AckAgentCommonApproverDeviceType) Valid() bool {
	switch e {
	case Android:
		return true
	case Ios:
		return true
	default:
		return false
	}
}

// Defines values for AckAgentCommonAttestationSecurityType.
const (
	AndroidStrongbox AckAgentCommonAttestationSecurityType = "android_strongbox"
	AndroidTee       AckAgentCommonAttestationSecurityType = "android_tee"
	IosSecureEnclave AckAgentCommonAttestationSecurityType = "ios_secure_enclave"
	PlayIntegrity    AckAgentCommonAttestationSecurityType = "play_integrity"
	Software         AckAgentCommonAttestationSecurityType = "software"
)

// Valid indicates whether the value is a known member of the AckAgentCommonAttestationSecurityType enum.
func (e AckAgentCommonAttestationSecurityType) Valid() bool {
	switch e {
	case AndroidStrongbox:
		return true
	case AndroidTee:
		return true
	case IosSecureEnclave:
		return true
	case PlayIntegrity:
		return true
	case Software:
		return true
	default:
		return false
	}
}

// Defines values for AckAgentCommonKeyPurpose.
const (
	Age AckAgentCommonKeyPurpose = "age"
	Gpg AckAgentCommonKeyPurpose = "gpg"
	Ssh AckAgentCommonKeyPurpose = "ssh"
)

// Valid indicates whether the value is a known member of the AckAgentCommonKeyPurpose enum.
func (e AckAgentCommonKeyPurpose) Valid() bool {
	switch e {
	case Age:
		return true
	case Gpg:
		return true
	case Ssh:
		return true
	default:
		return false
	}
}

// Defines values for AckAgentCommonSigningErrorCode.
const (
	N1 AckAgentCommonSigningErrorCode = 1
	N2 AckAgentCommonSigningErrorCode = 2
	N3 AckAgentCommonSigningErrorCode = 3
	N4 AckAgentCommonSigningErrorCode = 4
	N5 AckAgentCommonSigningErrorCode = 5
	N6 AckAgentCommonSigningErrorCode = 6
)

// Valid indicates whether the value is a known member of the AckAgentCommonSigningErrorCode enum.
func (e AckAgentCommonSigningErrorCode) Valid() bool {
	switch e {
	case N1:
		return true
	case N2:
		return true
	case N3:
		return true
	case N4:
		return true
	case N5:
		return true
	case N6:
		return true
	default:
		return false
	}
}

// Defines values for AckAgentCommonTransactionType.
const (
	AckAgentCommonTransactionTypeAgeUnwrap  AckAgentCommonTransactionType = "age_unwrap"
	AckAgentCommonTransactionTypeCustom     AckAgentCommonTransactionType = "custom"
	AckAgentCommonTransactionTypeEcdhDerive AckAgentCommonTransactionType = "ecdh_derive"
	AckAgentCommonTransactionTypeEnroll     AckAgentCommonTransactionType = "enroll"
	AckAgentCommonTransactionTypeGpgDecrypt AckAgentCommonTransactionType = "gpg_decrypt"
	AckAgentCommonTransactionTypeGpgSign    AckAgentCommonTransactionType = "gpg_sign"
	AckAgentCommonTransactionTypeSshAuth    AckAgentCommonTransactionType = "ssh_auth"
	AckAgentCommonTransactionTypeSshSign    AckAgentCommonTransactionType = "ssh_sign"
)

// Valid indicates whether the value is a known member of the AckAgentCommonTransactionType enum.
func (e AckAgentCommonTransactionType) Valid() bool {
	switch e {
	case AckAgentCommonTransactionTypeAgeUnwrap:
		return true
	case AckAgentCommonTransactionTypeCustom:
		return true
	case AckAgentCommonTransactionTypeEcdhDerive:
		return true
	case AckAgentCommonTransactionTypeEnroll:
		return true
	case AckAgentCommonTransactionTypeGpgDecrypt:
		return true
	case AckAgentCommonTransactionTypeGpgSign:
		return true
	case AckAgentCommonTransactionTypeSshAuth:
		return true
	case AckAgentCommonTransactionTypeSshSign:
		return true
	default:
		return false
	}
}

// Defines values for AgeUnwrapPayloadType.
const (
	AgeUnwrapPayloadTypeAgeUnwrap AgeUnwrapPayloadType = "age_unwrap"
)

// Valid indicates whether the value is a known member of the AgeUnwrapPayloadType enum.
func (e AgeUnwrapPayloadType) Valid() bool {
	switch e {
	case AgeUnwrapPayloadTypeAgeUnwrap:
		return true
	default:
		return false
	}
}

// Defines values for CustomPayloadType.
const (
	Custom CustomPayloadType = "custom"
)

// Valid indicates whether the value is a known member of the CustomPayloadType enum.
func (e CustomPayloadType) Valid() bool {
	switch e {
	case Custom:
		return true
	default:
		return false
	}
}

// Defines values for EcdhDerivePayloadType.
const (
	EcdhDerive EcdhDerivePayloadType = "ecdh_derive"
)

// Valid indicates whether the value is a known member of the EcdhDerivePayloadType enum.
func (e EcdhDerivePayloadType) Valid() bool {
	switch e {
	case EcdhDerive:
		return true
	default:
		return false
	}
}

// Defines values for EnrollPayloadType.
const (
	Enroll EnrollPayloadType = "enroll"
)

// Valid indicates whether the value is a known member of the EnrollPayloadType enum.
func (e EnrollPayloadType) Valid() bool {
	switch e {
	case Enroll:
		return true
	default:
		return false
	}
}

// Defines values for EnrollResponseStatus.
const (
	EnrollResponseStatusApproved EnrollResponseStatus = "approved"
	EnrollResponseStatusRejected EnrollResponseStatus = "rejected"
)

// Valid indicates whether the value is a known member of the EnrollResponseStatus enum.
func (e EnrollResponseStatus) Valid() bool {
	switch e {
	case EnrollResponseStatusApproved:
		return true
	case EnrollResponseStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for GpgDecryptPayloadType.
const (
	GpgDecrypt GpgDecryptPayloadType = "gpg_decrypt"
)

// Valid indicates whether the value is a known member of the GpgDecryptPayloadType enum.
func (e GpgDecryptPayloadType) Valid() bool {
	switch e {
	case GpgDecrypt:
		return true
	default:
		return false
	}
}

// Defines values for GpgSignPayloadType.
const (
	GpgSign GpgSignPayloadType = "gpg_sign"
)

// Valid indicates whether the value is a known member of the GpgSignPayloadType enum.
func (e GpgSignPayloadType) Valid() bool {
	switch e {
	case GpgSign:
		return true
	default:
		return false
	}
}

// Defines values for SignatureResponseStatus.
const (
	SignatureResponseStatusApproved SignatureResponseStatus = "approved"
	SignatureResponseStatusRejected SignatureResponseStatus = "rejected"
)

// Valid indicates whether the value is a known member of the SignatureResponseStatus enum.
func (e SignatureResponseStatus) Valid() bool {
	switch e {
	case SignatureResponseStatusApproved:
		return true
	case SignatureResponseStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for SshAuthPayloadType.
const (
	SshAuth SshAuthPayloadType = "ssh_auth"
)

// Valid indicates whether the value is a known member of the SshAuthPayloadType enum.
func (e SshAuthPayloadType) Valid() bool {
	switch e {
	case SshAuth:
		return true
	default:
		return false
	}
}

// Defines values for SshSignPayloadType.
const (
	SshSign SshSignPayloadType = "ssh_sign"
)

// Valid indicates whether the value is a known member of the SshSignPayloadType enum.
func (e SshSignPayloadType) Valid() bool {
	switch e {
	case SshSign:
		return true
	default:
		return false
	}
}

// AckAgentCommonApprovalAttestationV1 Service-issued approval attestation embedded into the Longfellow proof witness.
type AckAgentCommonApprovalAttestationV1 struct {
	// Bytes Base64-encoded `approval-attestation/v1` bytes embedded into the Longfellow proof witness.
	Bytes []byte `json:"bytes"`

	// Signature Base64-encoded raw 64-byte P-256 `r || s` signature over `SHA256(bytes)`.
	Signature []byte `json:"signature"`

	// Version Canonical approval attestation format version.
	Version AckAgentCommonApprovalAttestationV1Version `json:"version"`
}

// AckAgentCommonApprovalAttestationV1Version Canonical approval attestation format version.
type AckAgentCommonApprovalAttestationV1Version string

// AckAgentCommonApprovalAttestedKeyProof Canonical Longfellow approval proof carried inside encrypted approval responses.
type AckAgentCommonApprovalAttestedKeyProof struct {
	// Attestation Service-issued approval attestation embedded into the Longfellow proof witness.
	Attestation AckAgentCommonApprovalAttestationV1 `json:"attestation"`

	// Challenge Canonical Longfellow approval challenge.
	Challenge AckAgentCommonApprovalChallenge `json:"challenge"`

	// Proof Base64-encoded Longfellow approval proof bytes.
	Proof []byte `json:"proof"`

	// Statement Public Longfellow statement bound into the zero-knowledge proof.
	Statement AckAgentCommonApprovalProofStatement `json:"statement"`

	// Version Canonical approval proof format version.
	Version AckAgentCommonApprovalAttestedKeyProofVersion `json:"version"`
}

// AckAgentCommonApprovalAttestedKeyProofVersion Canonical approval proof format version.
type AckAgentCommonApprovalAttestedKeyProofVersion string

// AckAgentCommonApprovalChallenge Canonical Longfellow approval challenge.
type AckAgentCommonApprovalChallenge struct {
	// Nonce Opaque nonce bound into the approval challenge and proof statement.
	Nonce string `json:"nonce"`

	// PlaintextHash SHA-256 digest of the approved plaintext (format: `sha256:<hex>`).
	PlaintextHash string `json:"plaintextHash"`

	// RequestId Relay request ID that scopes the approval proof.
	RequestId string `json:"requestId"`

	// Version Canonical approval challenge format version.
	Version AckAgentCommonApprovalChallengeVersion `json:"version"`
}

// AckAgentCommonApprovalChallengeVersion Canonical approval challenge format version.
type AckAgentCommonApprovalChallengeVersion string

// AckAgentCommonApprovalProofStatement Public Longfellow statement bound into the zero-knowledge proof.
type AckAgentCommonApprovalProofStatement struct {
	// AppIdHashHex Lowercase hex-encoded SHA-256 hash of the mobile app identifier.
	AppIdHashHex string `json:"appIdHashHex"`

	// ApprovalHashHex Lowercase hex-encoded SHA-256 hash of the canonical approval challenge JSON.
	ApprovalHashHex string `json:"approvalHashHex"`

	// AudienceHashHex Lowercase hex-encoded SHA-256 hash of the verifier audience string.
	AudienceHashHex string `json:"audienceHashHex"`

	// ChallengeNonceHex Lowercase hex-encoded SHA-256 hash of `challenge.nonce`.
	ChallengeNonceHex string `json:"challengeNonceHex"`

	// IssuerPublicKeyHex Lowercase hex-encoded compressed P-256 issuer public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)).
	IssuerPublicKeyHex string `json:"issuerPublicKeyHex"`

	// Now Unix timestamp in seconds embedded into the approval proof statement.
	Now int64 `json:"now"`

	// PolicyVersion Policy version embedded into the approval proof statement.
	PolicyVersion int32 `json:"policyVersion"`
}

// AckAgentCommonApproverDeviceType Device platform type.
type AckAgentCommonApproverDeviceType string

// AckAgentCommonAttestationSecurityType Combined platform and security level for attestation.
type AckAgentCommonAttestationSecurityType string

// AckAgentCommonKeyMetadataAttestation Attestation proof that a key was created on attested device hardware.
type AckAgentCommonKeyMetadataAttestation struct {
	// Assertion App Attest assertion or software signature (base64)
	Assertion []byte `json:"assertion"`

	// AttestationObject Apple CBOR attestation object for hardware attestation (base64)
	AttestationObject *[]byte `json:"attestationObject,omitempty"`

	// AttestationPublicKeyHex Lowercase hex-encoded attestation key's public key (66 hex chars for P-256 33-byte compressed key).
	AttestationPublicKeyHex *string `json:"attestationPublicKeyHex,omitempty"`

	// AttestationTimestamp Unix timestamp in milliseconds
	AttestationTimestamp int64 `json:"attestationTimestamp"`

	// AttestationType Combined platform and security level for attestation.
	AttestationType AckAgentCommonAttestationSecurityType `json:"attestationType"`

	// Challenge SHA256(id || publicKey || createdAt || deviceAuthPublicKey)
	Challenge []byte `json:"challenge"`

	// PublicKeyHex Lowercase hex-encoded public key being attested (66 hex chars for P-256 33-byte key, or 64 hex chars for Ed25519 32-byte key).
	PublicKeyHex string `json:"publicKeyHex"`
}

// AckAgentCommonKeyPurpose Purpose of the key being enrolled.
type AckAgentCommonKeyPurpose string

// AckAgentCommonSigningErrorCode Error codes for signing failures (1=rejected, 2=timeout, 3=key_not_found, 4=invalid_payload, 5=attestation_failed, 6=internal_error).
type AckAgentCommonSigningErrorCode int

// AckAgentCommonTransactionType Type of signing or approval request.
type AckAgentCommonTransactionType string

// AgeUnwrapPayload Request to unwrap an age-encrypted file key.
type AgeUnwrapPayload struct {
	// ApprovalChallenge Canonical verifier-issued approval challenge to bind into the approval proof for this age unwrap request.
	ApprovalChallenge *AckAgentCommonApprovalChallenge `json:"approvalChallenge,omitempty"`

	// Display Display metadata for the approval UI.
	Display *GenericDisplaySchema `json:"display,omitempty"`

	// EphemeralPublicHex Lowercase hex-encoded sender's ephemeral X25519 public key (64 hex chars for 32-byte key).
	EphemeralPublicHex string `json:"ephemeralPublicHex"`

	// RecipientPublicHex Lowercase hex-encoded recipient's X25519 public key (64 hex chars for 32-byte key).
	RecipientPublicHex string `json:"recipientPublicHex"`

	// SourceInfo Source system and process ancestry information.
	SourceInfo *SourceInfo          `json:"sourceInfo,omitempty"`
	Type       AgeUnwrapPayloadType `json:"type"`

	// WrappedFileKey Base64-encoded wrapped file key for decryption.
	WrappedFileKey []byte `json:"wrappedFileKey"`
}

// AgeUnwrapPayloadType defines model for AgeUnwrapPayload.Type.
type AgeUnwrapPayloadType string

// AgeUnwrapResponse Response containing the unwrapped file key or error.
type AgeUnwrapResponse struct {
	// ApprovalProof Canonical Longfellow approval proof proving the response came from a genuine, service-authorized device. Present for successful approval responses. Inside the encrypted blob.
	ApprovalProof *AckAgentCommonApprovalAttestedKeyProof `json:"approvalProof,omitempty"`

	// ErrorCode Error code if the operation failed.
	ErrorCode *AckAgentCommonSigningErrorCode `json:"errorCode,omitempty"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// FileKey Base64-encoded unwrapped file key for decryption.
	FileKey *[]byte `json:"fileKey,omitempty"`
}

// BasePayload Base structure for all encrypted payloads.
type BasePayload struct {
	// ApprovalChallenge Canonical verifier-issued approval challenge to bind into the approver's Longfellow proof. When present, the approver must use this exact challenge instead of deriving one locally.
	ApprovalChallenge *AckAgentCommonApprovalChallenge `json:"approvalChallenge,omitempty"`

	// Display Display metadata for the approval UI.
	Display *GenericDisplaySchema `json:"display,omitempty"`

	// SourceInfo Source system and process ancestry information. Present on CLI-originated requests.
	SourceInfo *SourceInfo `json:"sourceInfo,omitempty"`

	// Type Type of request.
	Type AckAgentCommonTransactionType `json:"type"`
}

// CustomPayload Custom signing request with application-defined data.
type CustomPayload struct {
	// ApprovalChallenge Canonical verifier-issued approval challenge to bind into the approval proof for this custom signing request.
	ApprovalChallenge *AckAgentCommonApprovalChallenge `json:"approvalChallenge,omitempty"`

	// Display Required display schema for custom payloads.
	Display GenericDisplaySchema `json:"display"`

	// RawData Base64-encoded raw data to sign (preimage). The approver computes the SHA-256 digest and signs it.
	RawData []byte `json:"rawData"`

	// SourceInfo Source system and process ancestry information.
	SourceInfo *SourceInfo       `json:"sourceInfo,omitempty"`
	Type       CustomPayloadType `json:"type"`
}

// CustomPayloadType defines model for CustomPayload.Type.
type CustomPayloadType string

// DisplayField A field to display in the approval UI.
type DisplayField struct {
	// Expandable Field can be expanded to show more content.
	Expandable *bool `json:"expandable,omitempty"`

	// Icon SF Symbol name for iOS UI.
	Icon *string `json:"icon,omitempty"`

	// Label Label for the field.
	Label string `json:"label"`

	// Monospace Render value in monospace font.
	Monospace *bool `json:"monospace,omitempty"`

	// Multiline Render value as multiline text.
	Multiline *bool `json:"multiline,omitempty"`

	// Sensitive Value contains sensitive information.
	Sensitive *bool `json:"sensitive,omitempty"`

	// Value Value to display.
	Value string `json:"value"`
}

// EcdhDerivePayload ECDH key derivation request payload.
type EcdhDerivePayload struct {
	// ApprovalChallenge Canonical verifier-issued approval challenge to bind into the approval proof for this ECDH derive request.
	ApprovalChallenge *AckAgentCommonApprovalChallenge `json:"approvalChallenge,omitempty"`

	// Display Display metadata for the approval UI.
	Display *GenericDisplaySchema `json:"display,omitempty"`

	// Kdf Optional KDF parameters for key derivation.
	Kdf *EcdhKdfParams `json:"kdf,omitempty"`

	// PeerPublicHex Lowercase hex-encoded peer's public key for ECDH (66 hex chars for P-256 33-byte compressed key).
	PeerPublicHex string `json:"peerPublicHex"`

	// SourceInfo Source system and process ancestry information.
	SourceInfo *SourceInfo           `json:"sourceInfo,omitempty"`
	Type       EcdhDerivePayloadType `json:"type"`
}

// EcdhDerivePayloadType defines model for EcdhDerivePayload.Type.
type EcdhDerivePayloadType string

// EcdhDeriveResponse ECDH key derivation response.
type EcdhDeriveResponse struct {
	// ApprovalProof Canonical Longfellow approval proof proving the response came from a genuine, service-authorized device. Present for successful approval responses. Inside the encrypted blob.
	ApprovalProof *AckAgentCommonApprovalAttestedKeyProof `json:"approvalProof,omitempty"`

	// ErrorCode Error code if the operation failed.
	ErrorCode *AckAgentCommonSigningErrorCode `json:"errorCode,omitempty"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// SharedSecret Base64-encoded derived shared secret.
	SharedSecret *[]byte `json:"sharedSecret,omitempty"`
}

// EcdhKdfParams Parameters for ECDH key derivation function.
type EcdhKdfParams struct {
	// Algorithm KDF algorithm name.
	Algorithm *string `json:"algorithm,omitempty"`

	// Info Base64-encoded KDF info parameter.
	Info *[]byte `json:"info,omitempty"`

	// KeyLength Desired output key length in bytes.
	KeyLength *int32 `json:"keyLength,omitempty"`
}

// EnrollPayload Key enrollment request payload.
type EnrollPayload struct {
	// Algorithm Key algorithm to use.
	Algorithm *string `json:"algorithm,omitempty"`

	// ApprovalChallenge Canonical verifier-issued approval challenge to bind into the approval proof for this enrollment request.
	ApprovalChallenge *AckAgentCommonApprovalChallenge `json:"approvalChallenge,omitempty"`

	// Display Display metadata for the approval UI.
	Display *GenericDisplaySchema `json:"display,omitempty"`

	// IncludeCertification Include self-certification signature for GPG export.
	IncludeCertification *bool `json:"includeCertification,omitempty"`

	// Label Human-readable label for the key.
	Label *string `json:"label,omitempty"`

	// Purpose Purpose of the key (ssh, gpg, age).
	Purpose AckAgentCommonKeyPurpose `json:"purpose"`

	// SourceInfo Source system and process ancestry information.
	SourceInfo *SourceInfo       `json:"sourceInfo,omitempty"`
	Type       EnrollPayloadType `json:"type"`
}

// EnrollPayloadType defines model for EnrollPayload.Type.
type EnrollPayloadType string

// EnrollResponse Key enrollment response with public key or error.
type EnrollResponse struct {
	// Algorithm Key algorithm used.
	Algorithm *string `json:"algorithm,omitempty"`

	// Attestation Attestation proof that the key was created on attested device hardware.
	Attestation *AckAgentCommonKeyMetadataAttestation `json:"attestation,omitempty"`

	// EncryptionFingerprint 40-character hex fingerprint of the ECDH encryption subkey.
	EncryptionFingerprint *string `json:"encryptionFingerprint,omitempty"`

	// EncryptionPublicKeyHex Lowercase hex-encoded ECDH encryption subkey public key (66 hex chars for P-256 33-byte compressed key).
	EncryptionPublicKeyHex *string `json:"encryptionPublicKeyHex,omitempty"`

	// ErrorCode Error code if enrollment failed.
	ErrorCode *AckAgentCommonSigningErrorCode `json:"errorCode,omitempty"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// Fingerprint GPG fingerprint for GPG keys.
	Fingerprint *string `json:"fingerprint,omitempty"`

	// Id Key UUID (for GPG keys).
	Id *string `json:"id,omitempty"`

	// IosKeyId iOS Secure Enclave key identifier.
	IosKeyId *string `json:"iosKeyId,omitempty"`

	// KeyCreationTimestamp Unix timestamp when the key was created.
	KeyCreationTimestamp *int64 `json:"keyCreationTimestamp,omitempty"`

	// PublicKeyHex Lowercase hex-encoded public key (66 hex chars for P-256 33-byte key, or 64 hex chars for Ed25519 32-byte key).
	PublicKeyHex *string `json:"publicKeyHex,omitempty"`

	// Status Enrollment result.
	Status EnrollResponseStatus `json:"status"`

	// SubkeySignature Base64-encoded subkey binding signature.
	SubkeySignature *[]byte `json:"subkeySignature,omitempty"`

	// UserIdSignature Base64-encoded self-certification signature.
	UserIdSignature *[]byte `json:"userIdSignature,omitempty"`
}

// EnrollResponseStatus Enrollment result.
type EnrollResponseStatus string

// GenericDisplaySchema Schema for displaying approval requests to users.
type GenericDisplaySchema struct {
	// Fields Fields to display in the approval UI.
	Fields []DisplayField `json:"fields"`

	// HistoryTitle Shorter title for history list view.
	HistoryTitle *string `json:"historyTitle,omitempty"`

	// Icon SF Symbol name for iOS.
	Icon *string `json:"icon,omitempty"`

	// Subtitle Subtitle with additional context.
	Subtitle *string `json:"subtitle,omitempty"`

	// Title Main title for the approval screen.
	Title string `json:"title"`
}

// GpgDecryptPayload GPG decryption request payload.
type GpgDecryptPayload struct {
	// ApprovalChallenge Canonical verifier-issued approval challenge to bind into the approval proof for this GPG decrypt request.
	ApprovalChallenge *AckAgentCommonApprovalChallenge `json:"approvalChallenge,omitempty"`

	// Display Display metadata for the approval UI.
	Display *GenericDisplaySchema `json:"display,omitempty"`

	// EncryptedData Base64-encoded encrypted data to decrypt.
	EncryptedData []byte `json:"encryptedData"`

	// IosKeyId Hex-encoded public key selecting which on-device GPG encryption subkey the approver should use for ECDH. Required on the mailbox/poll path because the envelope does not carry a key identifier.
	IosKeyId *string `json:"iosKeyId,omitempty"`

	// Pkesk Public Key Encrypted Session Key data for decryption.
	Pkesk *PkeskData `json:"pkesk,omitempty"`

	// SourceInfo Source system and process ancestry information.
	SourceInfo *SourceInfo           `json:"sourceInfo,omitempty"`
	Type       GpgDecryptPayloadType `json:"type"`
}

// GpgDecryptPayloadType defines model for GpgDecryptPayload.Type.
type GpgDecryptPayloadType string

// GpgDecryptResponse GPG decryption response with session key.
type GpgDecryptResponse struct {
	// Algorithm OpenPGP symmetric algorithm ID.
	Algorithm *int32 `json:"algorithm,omitempty"`

	// ApprovalProof Canonical Longfellow approval proof proving the response came from a genuine, service-authorized device. Present for successful approval responses. Inside the encrypted blob.
	ApprovalProof *AckAgentCommonApprovalAttestedKeyProof `json:"approvalProof,omitempty"`

	// ErrorCode Error code if decryption failed.
	ErrorCode *AckAgentCommonSigningErrorCode `json:"errorCode,omitempty"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// SessionKey Base64-encoded unwrapped session key.
	SessionKey *[]byte `json:"sessionKey,omitempty"`
}

// GpgSignPayload GPG signing request payload.
type GpgSignPayload struct {
	// ApprovalChallenge Canonical verifier-issued approval challenge to bind into the approval proof for this GPG signing request.
	ApprovalChallenge *AckAgentCommonApprovalChallenge `json:"approvalChallenge,omitempty"`

	// Display Display metadata for the approval UI.
	Display *GenericDisplaySchema `json:"display,omitempty"`

	// IosKeyId Hex-encoded public key selecting which on-device GPG primary key the approver should use for signing. Required on the mailbox/poll path because the envelope does not carry a key identifier.
	IosKeyId *string `json:"iosKeyId,omitempty"`

	// RawData Base64-encoded raw data to sign (preimage). The approver builds the OpenPGP hash input from this preimage and signs the resulting digest.
	RawData []byte `json:"rawData"`

	// SourceInfo Source system and process ancestry information.
	SourceInfo *SourceInfo `json:"sourceInfo,omitempty"`

	// Type Request type identifier.
	Type GpgSignPayloadType `json:"type"`
}

// GpgSignPayloadType Request type identifier.
type GpgSignPayloadType string

// GpgSignatureResponse GPG signature response with armored signature.
type GpgSignatureResponse struct {
	// ApprovalProof Canonical Longfellow approval proof proving the response came from a genuine, service-authorized device. Present for successful approval responses. Inside the encrypted blob.
	ApprovalProof *AckAgentCommonApprovalAttestedKeyProof `json:"approvalProof,omitempty"`

	// ArmoredSignature ASCII-armored OpenPGP signature.
	ArmoredSignature *string `json:"armoredSignature,omitempty"`

	// ErrorCode Error code if signing failed.
	ErrorCode *AckAgentCommonSigningErrorCode `json:"errorCode,omitempty"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

// PkeskData Public Key Encrypted Session Key data from OpenPGP PKESK packet.
type PkeskData struct {
	// Algorithm OpenPGP public key algorithm (18 = ECDH).
	Algorithm int32 `json:"algorithm"`

	// EphemeralPoint Base64-encoded ephemeral ECDH public point (33 bytes compressed).
	EphemeralPoint []byte `json:"ephemeralPoint"`

	// KeyId Base64-encoded 8-byte recipient key ID.
	KeyId []byte `json:"keyId"`

	// Version PKESK packet version (typically 3).
	Version int32 `json:"version"`

	// WrappedKey Base64-encoded AES-wrapped session key.
	WrappedKey []byte `json:"wrappedKey"`
}

// ProcessEntry Entry in a process tree.
type ProcessEntry struct {
	// Command Command line of the process.
	Command string `json:"command"`

	// Pid Process ID.
	Pid int32 `json:"pid"`

	// Username Username running the process.
	Username string `json:"username"`
}

// RequestPayload Any valid request payload type.
type RequestPayload struct {
	union json.RawMessage
}

// ResponsePayload Any valid response payload type.
type ResponsePayload struct {
	union json.RawMessage
}

// SignatureResponse Generic signature response for SSH and custom requests.
type SignatureResponse struct {
	// ApprovalProof Canonical Longfellow approval proof proving the response came from a genuine, service-authorized device. Present for successful approval responses. Inside the encrypted blob.
	ApprovalProof *AckAgentCommonApprovalAttestedKeyProof `json:"approvalProof,omitempty"`

	// Counter SSH replay protection counter.
	Counter *int32 `json:"counter,omitempty"`

	// ErrorCode Error code if signing failed.
	ErrorCode *AckAgentCommonSigningErrorCode `json:"errorCode,omitempty"`

	// ErrorMessage Human-readable error message.
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// RequestId Request correlation ID.
	RequestId *string `json:"requestId,omitempty"`

	// Signature Base64-encoded signature.
	Signature *[]byte `json:"signature,omitempty"`

	// Status Approval status.
	Status *SignatureResponseStatus `json:"status,omitempty"`
}

// SignatureResponseStatus Approval status.
type SignatureResponseStatus string

// SourceInfo Information about the requesting system and process ancestry.
type SourceInfo struct {
	// Command Command line of the current process.
	Command *string `json:"command,omitempty"`

	// Hostname Source machine hostname.
	Hostname *string `json:"hostname,omitempty"`

	// LocalIp Local/private IP address.
	LocalIp *string `json:"localIp,omitempty"`

	// ProcessChain Full process tree from current process up to init.
	ProcessChain *[]ProcessEntry `json:"processChain,omitempty"`

	// Username User running the process.
	Username *string `json:"username,omitempty"`
}

// SshAuthPayload SSH authentication request payload.
type SshAuthPayload struct {
	// Application SSH application identifier (e.g., "ssh:").
	Application *string `json:"application,omitempty"`

	// ApprovalChallenge Canonical verifier-issued approval challenge to bind into the approval proof for this SSH authentication request.
	ApprovalChallenge *AckAgentCommonApprovalChallenge `json:"approvalChallenge,omitempty"`

	// Display Display metadata for the approval UI.
	Display *GenericDisplaySchema `json:"display,omitempty"`

	// Flags SSH SK flags bitmask (default 0x01 = user presence required).
	Flags *int32 `json:"flags,omitempty"`

	// IosKeyId iOS key identifier for key selection.
	IosKeyId *string `json:"iosKeyId,omitempty"`

	// KeyId Key ID to use for signing.
	KeyId *string `json:"keyId,omitempty"`

	// RawData Base64-encoded raw SSH challenge data (preimage). The approver constructs the SSH signature input from this preimage.
	RawData []byte `json:"rawData"`

	// SourceInfo Source system and process ancestry information.
	SourceInfo *SourceInfo        `json:"sourceInfo,omitempty"`
	Type       SshAuthPayloadType `json:"type"`
}

// SshAuthPayloadType defines model for SshAuthPayload.Type.
type SshAuthPayloadType string

// SshSignPayload SSH signing request payload.
type SshSignPayload struct {
	// Application SSH application identifier (e.g., "ssh:").
	Application *string `json:"application,omitempty"`

	// ApprovalChallenge Canonical verifier-issued approval challenge to bind into the approval proof for this SSH signing request.
	ApprovalChallenge *AckAgentCommonApprovalChallenge `json:"approvalChallenge,omitempty"`

	// Display Display metadata for the approval UI.
	Display *GenericDisplaySchema `json:"display,omitempty"`

	// Flags SSH SK flags bitmask (default 0x01 = user presence required).
	Flags *int32 `json:"flags,omitempty"`

	// IosKeyId iOS key identifier for key selection.
	IosKeyId *string `json:"iosKeyId,omitempty"`

	// KeyId Key ID to use for signing.
	KeyId *string `json:"keyId,omitempty"`

	// RawData Base64-encoded raw data to sign (preimage). The approver constructs the SSH signature input from this preimage.
	RawData []byte `json:"rawData"`

	// SourceInfo Source system and process ancestry information.
	SourceInfo *SourceInfo        `json:"sourceInfo,omitempty"`
	Type       SshSignPayloadType `json:"type"`
}

// SshSignPayloadType defines model for SshSignPayload.Type.
type SshSignPayloadType string

// TransactionMetadata Metadata extracted from encrypted payloads for display.
type TransactionMetadata struct {
	// ActionDescription Action description.
	ActionDescription *string `json:"actionDescription,omitempty"`

	// ActionTitle Action title for display.
	ActionTitle *string `json:"actionTitle,omitempty"`

	// AdditionalInfo Additional key-value metadata.
	AdditionalInfo *map[string]string `json:"additionalInfo,omitempty"`

	// AgeEphemeralPublicHex Lowercase hex-encoded age ephemeral X25519 public key (64 hex chars for 32-byte key).
	AgeEphemeralPublicHex *string `json:"ageEphemeralPublicHex,omitempty"`

	// AgeFileName Age file name.
	AgeFileName *string `json:"ageFileName,omitempty"`

	// AgeFileSize Age file size.
	AgeFileSize *int64 `json:"ageFileSize,omitempty"`

	// AgeRecipientPublicHex Lowercase hex-encoded age recipient X25519 public key (64 hex chars for 32-byte key).
	AgeRecipientPublicHex *string `json:"ageRecipientPublicHex,omitempty"`

	// AgeWrappedFileKey Base64-encoded age wrapped file key.
	AgeWrappedFileKey *[]byte `json:"ageWrappedFileKey,omitempty"`

	// Algorithm Enrollment algorithm.
	Algorithm *string `json:"algorithm,omitempty"`

	// AuthorEmail Git author email.
	AuthorEmail *string `json:"authorEmail,omitempty"`

	// AuthorName Git author name.
	AuthorName *string `json:"authorName,omitempty"`

	// AuthorTimestamp Git author timestamp.
	AuthorTimestamp *int64 `json:"authorTimestamp,omitempty"`

	// Branch Git branch name.
	Branch *string `json:"branch,omitempty"`

	// Command SSH command being executed.
	Command *string `json:"command,omitempty"`

	// CommandLine Full command line.
	CommandLine *string `json:"commandLine,omitempty"`

	// CommitMessage Git commit message.
	CommitMessage *string `json:"commitMessage,omitempty"`

	// CommitterEmail Git committer email.
	CommitterEmail *string `json:"committerEmail,omitempty"`

	// CommitterName Git committer name.
	CommitterName *string `json:"committerName,omitempty"`

	// CommitterTimestamp Git committer timestamp.
	CommitterTimestamp *int64 `json:"committerTimestamp,omitempty"`

	// ContentFull Full content if small enough.
	ContentFull *string `json:"contentFull,omitempty"`

	// ContentHash Hash of the content.
	ContentHash *string `json:"contentHash,omitempty"`

	// ContentPreview Preview of the content.
	ContentPreview *string `json:"contentPreview,omitempty"`

	// ContentSize Content size in bytes.
	ContentSize *int32 `json:"contentSize,omitempty"`

	// ContentType Content MIME type.
	ContentType *string `json:"contentType,omitempty"`

	// ContextPreimage Base64-encoded canonical JSON of the approval context preimage.
	ContextPreimage *string `json:"contextPreimage,omitempty"`

	// EncryptedTo Recipient key ID.
	EncryptedTo *string `json:"encryptedTo,omitempty"`

	// FileName File name for GPG operations.
	FileName *string `json:"fileName,omitempty"`

	// Hostname SSH target hostname.
	Hostname *string `json:"hostname,omitempty"`

	// InputSource Input source description.
	InputSource *string `json:"inputSource,omitempty"`

	// IsAnonymous Whether recipient is anonymous.
	IsAnonymous *bool `json:"isAnonymous,omitempty"`

	// IsGitCommit Whether this is a git commit signing.
	IsGitCommit *bool `json:"isGitCommit,omitempty"`

	// IsStdin Whether input is from stdin.
	IsStdin *bool `json:"isStdin,omitempty"`

	// Label Key label.
	Label *string `json:"label,omitempty"`

	// LocalIp Local IP address.
	LocalIp *string `json:"localIp,omitempty"`

	// LoginSessionId Login session ID.
	LoginSessionId *string `json:"loginSessionId,omitempty"`

	// MessageSize Encrypted message size.
	MessageSize *int32 `json:"messageSize,omitempty"`

	// OperationType Type of operation.
	OperationType *string `json:"operationType,omitempty"`

	// ParentHashes Git parent commit hashes.
	ParentHashes *[]string `json:"parentHashes,omitempty"`

	// Plaintext Plaintext content.
	Plaintext *string `json:"plaintext,omitempty"`

	// PlaintextHash Hash of the plaintext.
	PlaintextHash *string `json:"plaintextHash,omitempty"`

	// Port SSH port.
	Port *int32 `json:"port,omitempty"`

	// ProcessChain Process chain for SSH operations.
	ProcessChain *[]ProcessEntry `json:"processChain,omitempty"`

	// Purpose Enrollment purpose.
	Purpose *string `json:"purpose,omitempty"`

	// RecipientEmail Recipient email for encryption.
	RecipientEmail *string `json:"recipientEmail,omitempty"`

	// RepoName Repository name.
	RepoName *string `json:"repoName,omitempty"`

	// SasEmojis SAS verification emojis.
	SasEmojis *[]string `json:"sasEmojis,omitempty"`

	// SasWords SAS verification words.
	SasWords *[]string `json:"sasWords,omitempty"`

	// SenderKeyId Sender key ID for encryption.
	SenderKeyId *string `json:"senderKeyId,omitempty"`

	// SourceHostname Source machine hostname.
	SourceHostname *string `json:"sourceHostname,omitempty"`

	// TreeHash Git tree hash.
	TreeHash *string `json:"treeHash,omitempty"`

	// Username SSH username.
	Username *string `json:"username,omitempty"`
}

// AsGpgSignPayload returns the union data inside the RequestPayload as a GpgSignPayload
func (t RequestPayload) AsGpgSignPayload() (GpgSignPayload, error) {
	var body GpgSignPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGpgSignPayload overwrites any union data inside the RequestPayload as the provided GpgSignPayload
func (t *RequestPayload) FromGpgSignPayload(v GpgSignPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGpgSignPayload performs a merge with any union data inside the RequestPayload, using the provided GpgSignPayload
func (t *RequestPayload) MergeGpgSignPayload(v GpgSignPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSshAuthPayload returns the union data inside the RequestPayload as a SshAuthPayload
func (t RequestPayload) AsSshAuthPayload() (SshAuthPayload, error) {
	var body SshAuthPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSshAuthPayload overwrites any union data inside the RequestPayload as the provided SshAuthPayload
func (t *RequestPayload) FromSshAuthPayload(v SshAuthPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSshAuthPayload performs a merge with any union data inside the RequestPayload, using the provided SshAuthPayload
func (t *RequestPayload) MergeSshAuthPayload(v SshAuthPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSshSignPayload returns the union data inside the RequestPayload as a SshSignPayload
func (t RequestPayload) AsSshSignPayload() (SshSignPayload, error) {
	var body SshSignPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSshSignPayload overwrites any union data inside the RequestPayload as the provided SshSignPayload
func (t *RequestPayload) FromSshSignPayload(v SshSignPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSshSignPayload performs a merge with any union data inside the RequestPayload, using the provided SshSignPayload
func (t *RequestPayload) MergeSshSignPayload(v SshSignPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGpgDecryptPayload returns the union data inside the RequestPayload as a GpgDecryptPayload
func (t RequestPayload) AsGpgDecryptPayload() (GpgDecryptPayload, error) {
	var body GpgDecryptPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGpgDecryptPayload overwrites any union data inside the RequestPayload as the provided GpgDecryptPayload
func (t *RequestPayload) FromGpgDecryptPayload(v GpgDecryptPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGpgDecryptPayload performs a merge with any union data inside the RequestPayload, using the provided GpgDecryptPayload
func (t *RequestPayload) MergeGpgDecryptPayload(v GpgDecryptPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgeUnwrapPayload returns the union data inside the RequestPayload as a AgeUnwrapPayload
func (t RequestPayload) AsAgeUnwrapPayload() (AgeUnwrapPayload, error) {
	var body AgeUnwrapPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgeUnwrapPayload overwrites any union data inside the RequestPayload as the provided AgeUnwrapPayload
func (t *RequestPayload) FromAgeUnwrapPayload(v AgeUnwrapPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgeUnwrapPayload performs a merge with any union data inside the RequestPayload, using the provided AgeUnwrapPayload
func (t *RequestPayload) MergeAgeUnwrapPayload(v AgeUnwrapPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEcdhDerivePayload returns the union data inside the RequestPayload as a EcdhDerivePayload
func (t RequestPayload) AsEcdhDerivePayload() (EcdhDerivePayload, error) {
	var body EcdhDerivePayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEcdhDerivePayload overwrites any union data inside the RequestPayload as the provided EcdhDerivePayload
func (t *RequestPayload) FromEcdhDerivePayload(v EcdhDerivePayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEcdhDerivePayload performs a merge with any union data inside the RequestPayload, using the provided EcdhDerivePayload
func (t *RequestPayload) MergeEcdhDerivePayload(v EcdhDerivePayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEnrollPayload returns the union data inside the RequestPayload as a EnrollPayload
func (t RequestPayload) AsEnrollPayload() (EnrollPayload, error) {
	var body EnrollPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnrollPayload overwrites any union data inside the RequestPayload as the provided EnrollPayload
func (t *RequestPayload) FromEnrollPayload(v EnrollPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEnrollPayload performs a merge with any union data inside the RequestPayload, using the provided EnrollPayload
func (t *RequestPayload) MergeEnrollPayload(v EnrollPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCustomPayload returns the union data inside the RequestPayload as a CustomPayload
func (t RequestPayload) AsCustomPayload() (CustomPayload, error) {
	var body CustomPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCustomPayload overwrites any union data inside the RequestPayload as the provided CustomPayload
func (t *RequestPayload) FromCustomPayload(v CustomPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCustomPayload performs a merge with any union data inside the RequestPayload, using the provided CustomPayload
func (t *RequestPayload) MergeCustomPayload(v CustomPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RequestPayload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RequestPayload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSignatureResponse returns the union data inside the ResponsePayload as a SignatureResponse
func (t ResponsePayload) AsSignatureResponse() (SignatureResponse, error) {
	var body SignatureResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSignatureResponse overwrites any union data inside the ResponsePayload as the provided SignatureResponse
func (t *ResponsePayload) FromSignatureResponse(v SignatureResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSignatureResponse performs a merge with any union data inside the ResponsePayload, using the provided SignatureResponse
func (t *ResponsePayload) MergeSignatureResponse(v SignatureResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGpgSignatureResponse returns the union data inside the ResponsePayload as a GpgSignatureResponse
func (t ResponsePayload) AsGpgSignatureResponse() (GpgSignatureResponse, error) {
	var body GpgSignatureResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGpgSignatureResponse overwrites any union data inside the ResponsePayload as the provided GpgSignatureResponse
func (t *ResponsePayload) FromGpgSignatureResponse(v GpgSignatureResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGpgSignatureResponse performs a merge with any union data inside the ResponsePayload, using the provided GpgSignatureResponse
func (t *ResponsePayload) MergeGpgSignatureResponse(v GpgSignatureResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGpgDecryptResponse returns the union data inside the ResponsePayload as a GpgDecryptResponse
func (t ResponsePayload) AsGpgDecryptResponse() (GpgDecryptResponse, error) {
	var body GpgDecryptResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGpgDecryptResponse overwrites any union data inside the ResponsePayload as the provided GpgDecryptResponse
func (t *ResponsePayload) FromGpgDecryptResponse(v GpgDecryptResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGpgDecryptResponse performs a merge with any union data inside the ResponsePayload, using the provided GpgDecryptResponse
func (t *ResponsePayload) MergeGpgDecryptResponse(v GpgDecryptResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgeUnwrapResponse returns the union data inside the ResponsePayload as a AgeUnwrapResponse
func (t ResponsePayload) AsAgeUnwrapResponse() (AgeUnwrapResponse, error) {
	var body AgeUnwrapResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgeUnwrapResponse overwrites any union data inside the ResponsePayload as the provided AgeUnwrapResponse
func (t *ResponsePayload) FromAgeUnwrapResponse(v AgeUnwrapResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgeUnwrapResponse performs a merge with any union data inside the ResponsePayload, using the provided AgeUnwrapResponse
func (t *ResponsePayload) MergeAgeUnwrapResponse(v AgeUnwrapResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEcdhDeriveResponse returns the union data inside the ResponsePayload as a EcdhDeriveResponse
func (t ResponsePayload) AsEcdhDeriveResponse() (EcdhDeriveResponse, error) {
	var body EcdhDeriveResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEcdhDeriveResponse overwrites any union data inside the ResponsePayload as the provided EcdhDeriveResponse
func (t *ResponsePayload) FromEcdhDeriveResponse(v EcdhDeriveResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEcdhDeriveResponse performs a merge with any union data inside the ResponsePayload, using the provided EcdhDeriveResponse
func (t *ResponsePayload) MergeEcdhDeriveResponse(v EcdhDeriveResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEnrollResponse returns the union data inside the ResponsePayload as a EnrollResponse
func (t ResponsePayload) AsEnrollResponse() (EnrollResponse, error) {
	var body EnrollResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnrollResponse overwrites any union data inside the ResponsePayload as the provided EnrollResponse
func (t *ResponsePayload) FromEnrollResponse(v EnrollResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEnrollResponse performs a merge with any union data inside the ResponsePayload, using the provided EnrollResponse
func (t *ResponsePayload) MergeEnrollResponse(v EnrollResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResponsePayload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResponsePayload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
